import type { Word } from './types';

export const sampleWords: Word[] = [
  { id: 1, headword: 'abandon', meaning: '放弃，抛弃', example: 'He abandoned his car on the road.' },
  { id: 2, headword: 'ability', meaning: '能力，才能', example: 'She has the ability to solve problems.' },
  { id: 3, headword: 'absent', meaning: '缺席的，不在的', example: 'Why were you absent from class?' },
  { id: 4, headword: 'academy', meaning: '学院，研究院', example: 'He graduated from a military academy.' },
  { id: 5, headword: 'accept', meaning: '接受，同意', example: 'Please accept my apology.' },
  { id: 6, headword: 'accident', meaning: '事故，意外事件', example: 'There was a car accident yesterday.' },
  { id: 7, headword: 'achieve', meaning: '实现，达到', example: 'She achieved her goal.' },
  { id: 8, headword: 'across', meaning: '穿过，横过', example: 'He walked across the street.' },
  { id: 9, headword: 'act', meaning: '行动，表演', example: 'Think before you act.' },
  { id: 10, headword: 'active', meaning: '积极的，活跃的', example: 'She leads an active life.' },
  { id: 11, headword: 'activity', meaning: '活动', example: 'The school offers many activities.' },
  { id: 12, headword: 'actually', meaning: '实际上，事实上', example: 'Actually, I prefer tea.' },
  { id: 13, headword: 'add', meaning: '添加，增加', example: 'Add some sugar to the coffee.' },
  { id: 14, headword: 'address', meaning: '地址，演讲', example: 'What is your address?' },
  { id: 15, headword: 'admire', meaning: '钦佩，欣赏', example: 'I admire your courage.' },
  { id: 16, headword: 'admit', meaning: '承认，允许进入', example: 'He admitted his mistake.' },
  { id: 17, headword: 'adopt', meaning: '采用，收养', example: 'They adopted a child.' },
  { id: 18, headword: 'adult', meaning: '成年人', example: 'Adults should be responsible.' },
  { id: 19, headword: 'advance', meaning: '前进，提前', example: 'Technology has advanced greatly.' },
  { id: 20, headword: 'advantage', meaning: '优势，好处', example: 'Being tall has its advantages.' },
  { id: 21, headword: 'adventure', meaning: '冒险，奇遇', example: 'Life is an adventure.' },
  { id: 22, headword: 'advice', meaning: '建议，忠告', example: 'Can you give me some advice?' },
  { id: 23, headword: 'advise', meaning: '建议，劝告', example: 'I advise you to study hard.' },
  { id: 24, headword: 'afford', meaning: '负担得起', example: 'I can afford this car.' },
  { id: 25, headword: 'afraid', meaning: '害怕的', example: 'She is afraid of spiders.' },
  { id: 26, headword: 'Africa', meaning: '非洲', example: 'Lions live in Africa.' },
  { id: 27, headword: 'African', meaning: '非洲的，非洲人', example: 'She is African.' },
  { id: 28, headword: 'after', meaning: '在...之后', example: 'Let\'s meet after dinner.' },
  { id: 29, headword: 'afternoon', meaning: '下午', example: 'I have a meeting this afternoon.' },
  { id: 30, headword: 'again', meaning: '又，再次', example: 'Please try again.' },
  { id: 31, headword: 'against', meaning: '反对，靠着', example: 'He leaned against the wall.' },
  { id: 32, headword: 'age', meaning: '年龄，时代', example: 'What is your age?' },
  { id: 33, headword: 'aged', meaning: '...岁的', example: 'A man aged 30.' },
  { id: 34, headword: 'agency', meaning: '代理机构', example: 'I booked through a travel agency.' },
  { id: 35, headword: 'agent', meaning: '代理人，特工', example: 'He is a secret agent.' },
  { id: 36, headword: 'aggressive', meaning: '侵略的，好斗的', example: 'The team played aggressively.' },
  { id: 37, headword: 'ago', meaning: '以前', example: 'I saw him two days ago.' },
  { id: 38, headword: 'agree', meaning: '同意，赞成', example: 'I agree with you.' },
  { id: 39, headword: 'agreement', meaning: '同意，协议', example: 'We reached an agreement.' },
  { id: 40, headword: 'agriculture', meaning: '农业', example: 'Agriculture is important.' },
  { id: 41, headword: 'ahead', meaning: '向前，在前面', example: 'The car ahead stopped suddenly.' },
  { id: 42, headword: 'aid', meaning: '帮助，援助', example: 'First aid is important.' },
  { id: 43, headword: 'aim', meaning: '目标，瞄准', example: 'What is your aim in life?' },
  { id: 44, headword: 'air', meaning: '空气，空中', example: 'Fresh air is good for health.' },
  { id: 45, headword: 'aircraft', meaning: '飞机，航空器', example: 'The aircraft landed safely.' },
  { id: 46, headword: 'airline', meaning: '航空公司', example: 'Which airline did you take?' },
  { id: 47, headword: 'airplane', meaning: '飞机', example: 'The airplane took off on time.' },
  { id: 48, headword: 'airport', meaning: '机场', example: 'I met him at the airport.' },
  { id: 49, headword: 'alarm', meaning: '警报，闹钟', example: 'The alarm woke me up.' },
  { id: 50, headword: 'album', meaning: '专辑，相册', example: 'I bought his new album.' }
];